FROM ghcr.io/hpc-ai-adv-dev/sst-core:master-latest

# Update and install packages (assumes access to package repositories)
# Difference between deps in .dev and release Containerfile
RUN apt update && apt install -y \
    autoconf \
    cmake \
    libtool \
    libtool-bin \
    graphviz \
    libgraphviz-dev \
    valgrind \
    vim \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install git+https://github.com/alvaradoo/ahp_graph.git \
    matplotlib

RUN git clone https://github.com/hpc-ai-adv-dev/sst-benchmarks && \
    cd sst-benchmarks/phold/ && \
    make

COPY analyze_timings.py /workspace/.