# This Containerfile supports flexible MPICH version building with other SST deps
#
# BUILD ARGUMENTS:#
#   mpich:  MPICH version  (default: 4.0.2)
#   NCPUS:  Parallel make jobs (default: 2)
#
# STAGES DEFINED:
#   base       - installs OS + build dependencies + compiles MPICH
#
# Assumes you have tar.gz for MPICH already
#
# EXAMPLE USAGE:
#
# Build container with MPICH 4.0.2 and all other SST deps
# podman build \
#   --build-arg mpich=4.0.2 \
#   --build-arg NCPUS=4 \
#   -f Containerfile.dev \
#   -t sst-dev:latest \
#   .
#

# This assumes access to the ubuntu image
FROM ubuntu:22.04 AS base

# Build arguments to control download behavior
ARG mpich=4.0.2
ARG mpich_prefix=mpich-$mpich
ARG NCPUS=2

WORKDIR /tmp

# Update and install packages (assumes access to package repositories)
RUN apt update && apt install -y \
    build-essential \
    autoconf \
    automake \
    cmake \
    git \
    gfortran \
    python3 \
    python3-dev \
    python3-pip \
    libtool \
    libtool-bin \
    libfabric-dev \
    graphviz \
    libgraphviz-dev \
    valgrind \
    vim \
    wget \
    zlib1g-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy MPICH source
COPY ${mpich_prefix}.tar.gz /tmp/

# Build MPICH from source
RUN \
tar xvzf $mpich_prefix.tar.gz                                           && \
cd $mpich_prefix                                                        && \
./configure FFLAGS=-fallow-argument-mismatch FCFLAGS=-fallow-argument-mismatch && \
make -j$NCPUS                                                           && \
make install                                                            && \
make clean                                                              && \
cd ..                                                                   && \
rm -rf $mpich_prefix $mpich_prefix.tar.gz

RUN /sbin/ldconfig

# Set up workspace - SST will be built here during development
WORKDIR /workspace
ENTRYPOINT ["/bin/bash"]
